DROP TABLE if exists WEATHER
CREATE TABLE WEATHER(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT,
	TEMPERATURE DOUBLE NOT NULL,
	WIND_SPEED DOUBLE NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL default CURRENT_TIMESTAMP
);